# packages in addition to repo2docker/buildpacks/conda/environment.yml
name: pangeo
channels:
  - conda-forge
dependencies:
  - jupyterlab=1.1
  - jupyterhub=1.0
  - jupyter-server-proxy=1.1
  - nbgitpuller=0.7
  - dask=2.6
  - distributed=2.6
  - dask-kubernetes=0.10
  - dask-labextension=1.0
  - dask-gateway=0.5
  - tornado=6.0
  - bokeh=1.3
  - python-graphviz=0.13
  - pip=19.3
